spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_health_qa?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ""
  profiles:
    active: local

  flyway:
    enabled: true
